### ISSUE TITLE
Melhor solução pra não quebrar o script

### ISSUE THREAD

**Issue by felipendc** [mamutal91/vps#1]
https://github.com/mamutal91/vps/blob/816cbaff7c679cace00daad5ef78a7b4c3d3541d/.zshrc#L4

Ao invés de:
export ZSH="/home/mamutal91/.oh-my-zsh"

Eu recomendo:

export ZSH="$HOME/.oh-my-zsh"

Pois, se futuramente você trocar de nome de usuário, o seu script não é quebrado.

**Comment by mamutal91** [comment]
Obrigado
